/**
 * Guahh AI - Coding Engine (Pro Version)
 * Specialized engine for generating and explaining code in multiple languages.
 * Version: 2.3-ULTRA (Massive Template Expansion + Polished Aesthetics)
 */

const GuahhCodingEngine = {
    version: "2.3-ULTRA",

    // --- TEMPLATE LIBRARY ---
    templates: {
        python: [
            {
                name: "Standard Project (Pro)",
                isDefault: true,
                keywords: ['project', 'full', 'complete', 'app', 'application'],
                generate: (topic, className) => ({
                    'main.py': `import time\nfrom utils import Logger, Calculator\n\nclass ${className}App:\n    def __init__(self):\n        self.logger = Logger()\n        self.logger.log("Initializing ${topic}...")\n\n    def run(self):\n        print(f"Running {self.logger.get_timestamp()} - ${topic}")\n        # Core logic\n        res = Calculator.add(10, 5)\n        self.logger.log(f"Result: {res}")\n\nif __name__ == "__main__":\n    ${className}App().run()`,
                    'utils.py': `import datetime\n\nclass Logger:\n    def log(self, msg): print(f"[LOG]: {msg}")\n    def get_timestamp(self): return datetime.datetime.now()\n\nclass Calculator:\n    @staticmethod\n    def add(a, b): return a + b`,
                    'test_main.py': `import unittest\nfrom utils import Calculator\n\nclass Test${className}(unittest.TestCase):\n    def test_calc(self):\n        self.assertEqual(Calculator.add(1, 1), 2)\n\nif __name__ == "__main__':\n    unittest.main()`,
                    'README.md': `# ${topic}\nA complete Python project structure generated by Guahh AI.\n\n## Usage\nRun \`python main.py\``
                })
            },
            {
                name: "Web Scraper",
                keywords: ['scraper', 'crawl', 'scrape', 'bot', 'spider'],
                generate: (topic, className) => ({
                    'scraper.py': `import requests\nfrom bs4 import BeautifulSoup\nimport csv\n\ndef scrape_data(url):\n    print(f"Scraping {url} for ${topic}...")\n    headers = {'User-Agent': 'Mozilla/5.0'}\n    try:\n        response = requests.get(url, headers=headers)\n        response.raise_for_status()\n        soup = BeautifulSoup(response.text, 'html.parser')\n        \n        results = []\n        # Example: Find all headlines\n        for item in soup.select('h2'):\n            results.append(item.get_text(strip=True))\n            \n        return results\n    except Exception as e:\n        print(f"Error: {e}")\n        return []\n\nif __name__ == "__main__":\n    data = scrape_data('https://example.com')\n    print(f"Found {len(data)} items.")\n    with open('output.csv', 'w') as f:\n        writer = csv.writer(f)\n        writer.writerow(['Data'])\n        for row in data:\n            writer.writerow([row])`,
                    'requirements.txt': `requests\nbeautifulsoup4`
                })
            },
            {
                name: "GUI App (Tkinter)",
                keywords: ['gui', 'desktop', 'window', 'interface', 'calculator', 'ui'],
                generate: (topic, className) => ({
                    'gui_app.py': `import tkinter as tk\nfrom tkinter import messagebox\n\nclass ${className}GUI:\n    def __init__(self, root):\n        self.root = root\n        self.root.title("${topic}")\n        self.root.geometry("400x300")\n\n        self.label = tk.Label(root, text="Welcome to ${topic}", font=("Helvetica", 16))\n        self.label.pack(pady=20)\n\n        self.btn = tk.Button(root, text="Click Me", command=self.on_click)\n        self.btn.pack(pady=10)\n\n    def on_click(self):\n        messagebox.showinfo("Info", "${topic} Action Triggered!")\n\nif __name__ == "__main__":\n    root = tk.Tk()\n    app = ${className}GUI(root)\n    root.mainloop()`
                })
            },
            {
                name: "CLI Tool",
                keywords: ['cli', 'command line', 'terminal', 'tool', 'script'],
                generate: (topic, className) => ({
                    'cli.py': `import argparse\nimport sys\n\ndef main():\n    parser = argparse.ArgumentParser(description="${topic} CLI")\n    parser.add_argument('--action', help='Action to perform', default='run')\n    args = parser.parse_args()\n    \n    print(f"Executing {args.action} for ${topic}...")\n    # Logic here\n\nif __name__ == "__main__":\n    main()`,
                    'README.md': `# ${topic} CLI\nUsage: \`python cli.py --action=start\``
                })
            },
            {
                name: "Flask API",
                keywords: ['api', 'flask', 'server', 'backend', 'web'],
                generate: (topic, className) => ({
                    'app.py': `from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return jsonify({"service": "${topic}", "status": "active"})\n\nif __name__ == "__main__":\n    app.run(debug=True)`,
                    'requirements.txt': `flask\ngunicorn`
                })
            },
            {
                name: "Data Script",
                keywords: ['data', 'csv', 'json', 'pandas', 'analysis', 'processing'],
                generate: (topic, className) => ({
                    'process_data.py': `import json\nimport csv\n\nclass ${className}Processor:\n    def process(self, data):\n        print(f"Processing {len(data)} records for ${topic}...")\n        return [d for d in data if d]\n\nif __name__ == "__main__":\n    proc = ${className}Processor()\n    proc.process([1, 2, 3])`,
                    'data.json': `[{"id": 1, "value": "sample"}]`
                })
            }
        ],
        html: [
            {
                name: "Single File Website",
                isDefault: true,
                keywords: ['website', 'site', 'web', 'page', 'simple'],
                generate: (topic) => ({
                    'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${topic}</title>
    <style>
        :root { --primary: #2563eb; --text: #1f2937; --bg: #f3f4f6; --card: #ffffff; }
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; margin: 0; background: var(--bg); color: var(--text); line-height: 1.6; }
        header { background: var(--card); padding: 1.5rem 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 100; }
        .logo { font-weight: 800; font-size: 1.5rem; letter-spacing: -0.05em; color: var(--primary); }
        nav { display: flex; gap: 1.5rem; }
        nav a { text-decoration: none; color: #4b5563; font-weight: 500; transition: color 0.2s; }
        nav a:hover { color: var(--primary); }
        .hero { text-align: center; padding: 6rem 1rem; background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%); color: white; margin-bottom: 2rem; clip-path: polygon(0 0, 100% 0, 100% 85%, 0 100%); }
        h1 { font-size: 3.5rem; margin-bottom: 1rem; letter-spacing: -0.02em; }
        .btn { display: inline-block; background: white; color: var(--primary); padding: 0.8rem 2rem; border-radius: 999px; text-decoration: none; font-weight: bold; margin-top: 1rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); transition: transform 0.2s; }
        .btn:hover { transform: translateY(-2px); }
        .container { max-width: 1000px; margin: 0 auto; padding: 2rem; }
        .card { background: var(--card); padding: 2rem; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); margin-bottom: 1.5rem; }
        footer { text-align: center; padding: 2rem; color: #9ca3af; font-size: 0.9rem; }
    </style>
</head>
<body>
    <header>
        <div class="logo">${topic}</div>
        <nav><a href="#">Features</a><a href="#">About</a><a href="#">Contact</a></nav>
    </header>
    <div class="hero">
        <h1>Redefining ${topic}</h1>
        <p style="font-size: 1.2rem; opacity: 0.9;">The intelligent solution for the modern web.</p>
        <a href="#" class="btn">Get Started</a>
    </div>
    <div class="container">
        <div class="card">
            <h2>Why Choose Us?</h2>
            <p>We provide state-of-the-art ${topic} services that scale with your needs. Our single-file architecture ensures speed and reliability.</p>
        </div>
        <div class="card">
            <h2>Our Mission</h2>
            <p>To revolutionize ${topic} through innovation and design excellence.</p>
        </div>
    </div>
    <footer>&copy; 2026 ${topic} Digital. All rights reserved.</footer>
</body>
</html>`
                })
            },
            {
                name: "Dashboard Layout",
                keywords: ['dashboard', 'admin', 'panel', 'analytics', 'manage'],
                generate: (topic) => ({
                    'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <title>${topic} Dashboard</title>
    <style>
        :root { --sidebar: #1e293b; --bg: #f1f5f9; }
        body { display: flex; min-height: 100vh; margin: 0; font-family: system-ui, sans-serif; background: var(--bg); }
        aside { width: 260px; background: var(--sidebar); color: #94a3b8; padding: 1.5rem; display: flex; flex-direction: column; }
        aside h2 { color: white; margin-bottom: 2rem; font-size: 1.2rem; text-transform: uppercase; letter-spacing: 0.1em; }
        .menu-item { display: block; padding: 0.8rem 1rem; margin-bottom: 0.5rem; color: #cbd5e1; text-decoration: none; border-radius: 6px; transition: 0.2s; }
        .menu-item:hover, .menu-item.active { background: #334155; color: white; }
        main { flex: 1; padding: 2rem; }
        header { display: flex; justify-content: space-between; margin-bottom: 2rem; align-items: center; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem; }
        .card { background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
        .stat-value { font-size: 2.5rem; font-weight: bold; color: #0f172a; }
        .stat-label { color: #64748b; font-size: 0.9rem; margin-bottom: 0.5rem; }
    </style>
</head>
<body>
    <aside>
        <h2>${topic}</h2>
        <nav>
            <a href="#" class="menu-item active">Overview</a>
            <a href="#" class="menu-item">Analytics</a>
            <a href="#" class="menu-item">Users</a>
            <a href="#" class="menu-item">Settings</a>
        </nav>
    </aside>
    <main>
        <header>
            <h1>Dashboard Overview</h1>
            <div style="width:40px;height:40px;background:#cbd5e1;border-radius:50%;"></div>
        </header>
        <div class="stats-grid">
            <div class="card"><div class="stat-label">Total Users</div><div class="stat-value">12,345</div></div>
            <div class="card"><div class="stat-label">Revenue</div><div class="stat-value">$45.2k</div></div>
            <div class="card"><div class="stat-label">Active Sessions</div><div class="stat-value">1,024</div></div>
            <div class="card"><div class="stat-label">Growth</div><div class="stat-value" style="color:#10b981;">+15%</div></div>
        </div>
    </main>
</body>
</html>`
                })
            },
            {
                name: "Login Form",
                keywords: ['login', 'signin', 'sign up', 'register', 'auth', 'authentication'],
                generate: (topic) => ({
                    'index.html': `<!DOCTYPE html>
<html>
<head><title>Login - ${topic}</title>
<style>
    body { height: 100vh; display: flex; align-items: center; justify-content: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); font-family: system-ui; margin: 0; }
    .glass-card { background: rgba(255, 255, 255, 0.95); padding: 3rem; border-radius: 20px; box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1); width: 100%; max-width: 400px; text-align: center; }
    h1 { color: #333; margin-bottom: 0.5rem; }
    p { color: #666; margin-bottom: 2rem; }
    input { width: 100%; padding: 12px; margin-bottom: 1rem; border: 1px solid #ddd; border-radius: 8px; box-sizing: border-box; font-size: 1rem; transition: 0.2s; }
    input:focus { border-color: #764ba2; outline: none; box-shadow: 0 0 0 3px rgba(118, 75, 162, 0.2); }
    button { width: 100%; padding: 12px; background: #764ba2; color: white; border: none; border-radius: 8px; font-size: 1rem; font-weight: bold; cursor: pointer; transition: 0.2s; }
    button:hover { background: #5a387d; }
    .links { margin-top: 1.5rem; font-size: 0.9rem; }
    a { color: #764ba2; text-decoration: none; }
</style>
</head>
<body>
    <div class="glass-card">
        <h1>Welcome Back</h1>
        <p>Sign in to your ${topic} account</p>
        <input type="email" placeholder="Email Address">
        <input type="password" placeholder="Password">
        <button onclick="alert('Logging in...')">Sign In</button>
        <div class="links">
            <a href="#">Forgot Password?</a> &bull; <a href="#">Create Account</a>
        </div>
    </div>
</body>
</html>`
                })
            },
            {
                name: "E-Commerce",
                keywords: ['store', 'shop', 'ecommerce', 'product', 'buy', 'selling'],
                generate: (topic) => ({
                    'index.html': `<!DOCTYPE html>
<html>
<head><title>${topic} Store</title>
<style>
    body { font-family: system-ui; margin: 0; background: #fafafa; }
    nav { padding: 1.5rem; background: white; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 2rem; padding: 2rem; max-width: 1200px; margin: 0 auto; }
    .product { background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.05); transition: 0.3s; }
    .product:hover { transform: translateY(-5px); box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
    .img-placeholder { height: 200px; background: #eee; display: flex; align-items: center; justify-content: center; color: #999; }
    .details { padding: 1.5rem; }
    .price { font-size: 1.25rem; font-weight: bold; color: #333; margin: 0.5rem 0; }
    button { width: 100%; padding: 10px; background: #000; color: white; border: none; border-radius: 6px; cursor: pointer; }
</style>
</head>
<body>
    <nav><strong>${topic}</strong> <span>Cart (0)</span></nav>
    <div class="grid">
        <div class="product"><div class="img-placeholder">Product Image</div><div class="details"><h3>Premium Item</h3><div class="price">$99.00</div><button>Add to Cart</button></div></div>
        <div class="product"><div class="img-placeholder">Product Image</div><div class="details"><h3>Deluxe Edition</h3><div class="price">$149.00</div><button>Add to Cart</button></div></div>
        <div class="product"><div class="img-placeholder">Product Image</div><div class="details"><h3>Standard Pack</h3><div class="price">$49.00</div><button>Add to Cart</button></div></div>
    </div>
</body>
</html>`
                })
            },
            {
                name: "Portfolio",
                keywords: ['portfolio', 'resume', 'cv', 'personal'],
                generate: (topic) => ({
                    'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <title>${topic} Portfolio</title>
    <style>
        body { display: flex; min-height: 100vh; margin: 0; font-family: 'Courier New', monospace; background: #1a1a1a; color: #eee; }
        aside { width: 260px; background: #111; padding: 2rem; border-right: 1px solid #333; }
        main { flex: 1; padding: 4rem; overflow-y: auto; }
        h1 { font-size: 3rem; margin-top: 0; }
        .nav-item { display: block; padding: 10px 0; color: #888; text-decoration: none; }
        .nav-item:hover, .nav-item.active { color: white; }
        .project { background: #222; padding: 1.5rem; margin-bottom: 1.5rem; border-radius: 4px; border: 1px solid #333; }
        .tag { display: inline-block; padding: 2px 8px; background: #333; font-size: 0.8rem; border-radius: 4px; margin-right: 5px; }
    </style>
</head>
<body>
    <aside>
        <h2>${topic}</h2>
        <p style="color:#666; font-size: 0.9rem;">Creative Developer</p>
        <nav style="margin-top: 2rem;">
            <a href="#" class="nav-item active">Work</a>
            <a href="#" class="nav-item">About</a>
            <a href="#" class="nav-item">Contact</a>
        </nav>
    </aside>
    <main>
        <h1>Selected Works</h1>
        <div class="project">
            <h3>Project Alpha</h3>
            <p>Innovation in ${topic}. A deep dive into modern systems.</p>
            <div><span class="tag">React</span> <span class="tag">Node</span></div>
        </div>
        <div class="project">
            <h3>Project Beta</h3>
            <p>Redefining boundaries with clean architecture.</p>
            <div><span class="tag">Python</span> <span class="tag">AI</span></div>
        </div>
    </main>
</body>
</html>`
                })
            }
        ],
        game: [
            {
                name: "Snake",
                keywords: ['snake'],
                generate: (topic) => ({
                    'snake.html': `<!DOCTYPE html>
<html><head><title>Snake</title><style>body{background:#222;color:#fff;display:flex;flex-direction:column;align-items:center;font-family:sans-serif;} canvas{background:#000;border:2px solid #555;box-shadow:0 0 20px rgba(0,0,0,0.5);}</style></head>
<body><h2>Snake</h2><canvas id="c" width="400" height="400"></canvas><p>Use Arrow Keys to Move</p>
<script>
const c=document.getElementById('c'), ctx=c.getContext('2d');
let snake=[{x:10,y:10}], apple={x:15,y:15}, dx=0, dy=0, score=0;
setInterval(()=>{
 snake.unshift({x:snake[0].x+dx,y:snake[0].y+dy});
 if(snake[0].x==apple.x&&snake[0].y==apple.y){apple={x:Math.random()*20|0,y:Math.random()*20|0};score++}else{snake.pop()}
 if(snake[0].x<0||snake[0].x>=20||snake[0].y<0||snake[0].y>=20){snake=[{x:10,y:10}];score=0;} // Reset
 ctx.fillStyle='black';ctx.fillRect(0,0,400,400);
 ctx.fillStyle='lime';snake.forEach(p=>ctx.fillRect(p.x*20,p.y*20,18,18));
 ctx.fillStyle='red';ctx.fillRect(apple.x*20,apple.y*20,18,18);
 ctx.fillStyle='white';ctx.fillText('Score: '+score, 10, 20);
},100);
window.onkeydown=e=>{const k=e.key;if(k=='ArrowUp'&&dy!=1){dy=-1;dx=0}if(k=='ArrowDown'&&dy!=-1){dy=1;dx=0}if(k=='ArrowLeft'&&dx!=1){dx=-1;dy=0}if(k=='ArrowRight'&&dx!=-1){dx=1;dy=0}}
</script></body></html>`
                })
            },
            {
                name: "Breakout",
                keywords: ['breakout', 'brick', 'paddle', 'destroy'],
                generate: (topic) => ({
                    'breakout.html': `<!DOCTYPE html>
<html>
<head><title>Breakout</title><style>body{background:#111;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;font-family:monospace;color:white;}</style></head>
<body>
<canvas id="c" width="480" height="320" style="border:1px solid white;"></canvas>
<script>
const c=document.getElementById("c"), x=c.getContext("2d");
let bx=240, by=160, dx=2, dy=-2, px=200, right=false, left=false;
const bricks=[], rows=3, cols=5;
for(let c=0; c<cols; c++) { bricks[c]=[]; for(let r=0; r<rows; r++) bricks[c][r]={ x:0, y:0, status:1 }; }
document.addEventListener("keydown", e=>{if(e.key=="ArrowRight")right=true;else if(e.key=="ArrowLeft")left=true}, false);
document.addEventListener("keyup", e=>{if(e.key=="ArrowRight")right=false;else if(e.key=="ArrowLeft")left=false}, false);
function draw(){
 x.clearRect(0,0,c.width,c.height);
 for(let c=0; c<cols; c++) for(let r=0; r<rows; r++) {
  let b=bricks[c][r];
  if(b.status==1) {
   let bX=(c*75)+50, bY=(r*20)+30; b.x=bX; b.y=bY;
   x.fillStyle="#0095DD"; x.fillRect(bX,bY,75,20);
   if(bx>bX && bx<bX+75 && by>bY && by<bY+20) { dy=-dy; b.status=0; }
  }
 }
 x.beginPath(); x.arc(bx,by,10,0,Math.PI*2); x.fillStyle="#fff"; x.fill(); x.closePath();
 x.fillStyle="#0095DD"; x.fillRect(px, 300, 75, 10);
 if(bx+dx>480-10 || bx+dx<10) dx=-dx;
 if(by+dy<10) dy=-dy;
 else if(by+dy>320-10) { if(bx>px && bx<px+75) dy=-dy; else { bx=240; by=160; dy=-2; } } // Reset on loss
 if(right && px<480-75) px+=7; else if(left && px>0) px-=7;
 bx+=dx; by+=dy;
 requestAnimationFrame(draw);
}
draw();
</script></body></html>`
                })
            },
            {
                name: "Space Shooter",
                keywords: ['space', 'shooter', 'alien', 'fly', 'ship'],
                generate: (topic) => ({
                    'space.html': `<!DOCTYPE html>
<html><body style="background:black;overflow:hidden;margin:0;">
<canvas id="c"></canvas>
<script>
const c=document.getElementById('c'), x=c.getContext('2d');
c.width=window.innerWidth; c.height=window.innerHeight;
const p={x:c.width/2,y:c.height-50,w:30,h:30}, bullets=[], enemies=[];
let score=0;
setInterval(()=>{ if(Math.random()<0.05) enemies.push({x:Math.random()*c.width,y:0,s:2+Math.random()*2}); }, 20); // Spawn
function loop(){
 x.fillStyle='rgba(0,0,0,0.2)'; x.fillRect(0,0,c.width,c.height); // Trail effect
 x.fillStyle='cyan'; x.fillRect(p.x,p.y,p.w,p.h); // Player
 bullets.forEach((b,i)=>{ 
  b.y-=7; x.fillStyle='yellow'; x.fillRect(b.x,b.y,5,10);
  if(b.y<0) bullets.splice(i,1);
 });
 enemies.forEach((e,i)=>{
  e.y+=e.s; x.fillStyle='red'; x.fillRect(e.x,e.y,30,30);
  if(e.y>c.height) enemies.splice(i,1);
  bullets.forEach((b,j)=>{ if(b.x>e.x&&b.x<e.x+30&&b.y>e.y&&b.y<e.y+30){enemies.splice(i,1);bullets.splice(j,1);score+=10;} });
 });
 x.fillStyle='white'; x.font='20px Arial'; x.fillText('Score: '+score, 20, 30);
 requestAnimationFrame(loop);
}
window.onmousemove=e=>p.x=e.clientX;
window.onmousedown=()=>bullets.push({x:p.x+12,y:p.y});
loop();
</script></body></html>`
                })
            },
            {
                name: "2048",
                keywords: ['2048', 'puzzle', 'grid', 'merge'],
                generate: (topic) => ({
                    '2048.html': `<!DOCTYPE html>
<html><head><title>2048</title><style>
body{font-family:sans-serif;background:#faf8ef;text-align:center;}
#g{width:400px;height:400px;background:#bbada0;margin:auto;border-radius:6px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:10px;}
.c{background:#cdc1b4;border-radius:3px;display:flex;justify-content:center;align-items:center;font-size:30px;font-weight:bold;color:#776e65;}
.v2{background:#eee4da;}.v4{background:#ede0c8;}.v8{background:#f2b179;color:white;}.v16{background:#f59563;color:white;}
</style></head>
<body><h2>2048</h2><div id="g"></div><script>
let b=Array(16).fill(0);
function spawn(){let e=b.map((v,i)=>v==0?i:null).filter(v=>v!=null);if(e.length)b[e[Math.random()*e.length|0]]=Math.random()>.9?4:2;}
function draw(){document.getElementById('g').innerHTML=b.map(v=>'<div class="c v'+v+'">'+(v||'')+'</div>').join('');}
// Simplified logic: just spawn random for demo (Real 2048 logic is distinct but this mimics visual)
spawn();spawn();draw();
window.onkeydown=()=>{spawn();draw();}
</script><p>Press any key to add numbers (Demo)</p></body></html>`
                })
            },
            {
                name: "Pong",
                keywords: ['pong', 'tennis'],
                generate: (topic) => ({
                    'pong.html': `<!DOCTYPE html>
<html><body style="background:#000;color:#fff;text-align:center;">
<h2>Pong</h2>
<canvas id="c" width="600" height="400" style="border:2px solid #fff;"></canvas>
<script>
const c=document.getElementById('c'), x=c.getContext('2d');
let bx=300, by=200, bdx=3, bdy=3, py=150, aiy=150;
setInterval(()=>{
 bx+=bdx;by+=bdy;
 if(by<0||by>400)bdy=-bdy;
 if(bx<0){bx=300;bdx=3} // Reset
 if(bx>600){if(by>aiy&&by<aiy+100){bdx=-bdx*1.1}else{bx=300;bdx=-3}}
 if(bx<20){if(by>py&&by<py+100){bdx=-bdx*1.1}else{}}
 aiy+=(by-aiy-50)*0.1;
 x.clearRect(0,0,600,400);
 x.fillRect(0,py,10,100);x.fillRect(590,aiy,10,100);x.fillRect(bx,by,10,10);
},16);
c.onmousemove=e=>py=e.clientY-c.getBoundingClientRect().top-50;
</script></body></html>`
                })
            },
            {
                name: "Clicker",
                isDefault: true,
                keywords: ['clicker', 'idle', 'click'],
                generate: (topic) => ({
                    'clicker.html': `<!DOCTYPE html>
<html><body style="text-align:center;font-family:sans-serif;padding:50px;">
<h1>${topic} Clicker</h1>
<h2 id="s">0</h2>
<button onclick="s.innerText=++n;a()" style="font-size:24px;padding:20px;">CLICK ME</button>
<script>let n=0;function a(){let d=document.createElement('div');d.innerText='+1';d.style.position='absolute';d.style.left=Math.random()*window.innerWidth+'px';d.style.top=Math.random()*window.innerHeight+'px';document.body.appendChild(d);setTimeout(()=>d.remove(),1000);}</script>
</body></html>`
                })
            }
        ]
    },

    // --- LANGUAGE DETECTION & TOPIC EXTRACTION ---

    detectLanguage(query) {
        const q = query.toLowerCase();
        // Web & JS
        if (q.includes('react') || q.includes('jsx')) return 'react';
        if (q.includes('game') || q.includes('play') || q.includes('snake') || q.includes('pong') || q.includes('clicker') || q.includes('breakout') || q.includes('shooter')) return 'game';
        if (q.includes('html') || q.includes('website') || q.includes('page') || q.includes('portfolio') || q.includes('landing') || q.includes('dashboard') || q.includes('login') || q.includes('store')) return 'html';
        if (q.includes('node') || q.includes('express') || q.includes('backend')) return 'node';
        if (q.includes('javascript') || q.includes('js')) return 'javascript';
        if (q.includes('css') || q.includes('style')) return 'css';

        // Systems & App
        if (q.includes('python') || q.includes('flask') || q.includes('pandas') || q.includes('scraper')) return 'python';
        if (q.includes('swift') || q.includes('ios')) return 'swift';
        if (q.includes('java')) return 'java';
        if (q.includes('c++') || q.includes('cpp')) return 'cpp';
        if (q.includes('ruby') || q.includes('rails')) return 'ruby';
        if (q.includes('sql') || q.includes('query')) return 'sql';

        // Default keywords
        if (q.includes('def ')) return 'python';
        if (q.includes('function')) return 'javascript';

        return 'python'; // Default
    },

    extractTopic(query) {
        const q = query.toLowerCase();
        const patterns = [
            /(?:about|for|showing|regarding|titled|called)\s+(.+)/,
            /(?:talks?|talking)\s+about\s+(.+)/,
            /(?:create|make|write|code).*\s+(?:project|website|page|script|program|app|game)\s+(?:about|for)\s+(.+)/
        ];
        for (const p of patterns) {
            const match = q.match(p);
            if (match && match[1]) return this.cleanTopic(match[1]);
        }
        return "My Project";
    },

    cleanTopic(rawTopic) {
        let topic = rawTopic.trim().replace(/[.!?]+$/, '');
        return topic.charAt(0).toUpperCase() + topic.slice(1);
    },

    // --- HELPER: SMART TEMPLATE SELECTOR (Intent > Default > Random) ---
    selectTemplate(language, query) {
        const libs = this.templates[language];
        if (!libs) return null;

        const q = query.toLowerCase();

        // 1. Strict Intent Matching (Keyword)
        for (const t of libs) {
            if (t.keywords && t.keywords.some(k => q.includes(k))) {
                console.log(`[CodingEngine] Intent Match: ${t.name}`);
                return t;
            }
        }

        // 2. Default (Best Quality)
        const defaultTemplate = libs.find(t => t.isDefault);
        if (defaultTemplate) {
            console.log(`[CodingEngine] Default Selected: ${defaultTemplate.name}`);
            return defaultTemplate;
        }

        // 3. Fallback to First (Shouldn't usually happen if defaults are set)
        return libs[0];
    },

    // --- STRATEGIES ---
    strategies: {
        python: {
            generate(topic, q, engine) {
                const template = engine.selectTemplate('python', q);
                const className = topic.replace(/\s+/g, '');
                return template.generate(topic, className);
            }
        },
        html: {
            generate(topic, q, engine) {
                const template = engine.selectTemplate('html', q);
                return template.generate(topic);
            }
        },
        game: {
            generate(topic, q, engine) {
                const template = engine.selectTemplate('game', q);
                return template ? template.generate(topic) : engine.templates.game[0].generate(topic); // Fallback
            }
        },

        // --- Single Strategy Languages ---
        node: {
            generate(topic) { return { 'server.js': `const express = require('express');\n// ${topic} server` }; }
        },
        react: {
            generate(topic) { return { 'App.jsx': `export default () => <h1>${topic}</h1>` }; }
        },
        java: {
            generate(topic) { return { 'Main.java': `public class Main { public static void main(String[] args) { System.out.println("${topic}"); } }` }; }
        },
        swift: {
            generate(topic) { return { 'ContentView.swift': `import SwiftUI; struct ContentView: View { var body: some View { Text("${topic}") } }` }; }
        },
        sql: {
            generate(topic) { return { 'query.sql': `SELECT * FROM ${topic}` }; }
        },
        cpp: {
            generate(topic) { return { 'main.cpp': `#include <iostream>\nint main(){std::cout<<"${topic}";}` }; }
        },
        ruby: {
            generate(topic) { return { 'script.rb': `puts "${topic}"` }; }
        },
        javascript: {
            generate(topic) { return { 'script.js': `console.log("${topic}")` }; }
        },
        css: {
            generate(topic) { return { 'style.css': `body { background: #f0f0f0; /* ${topic} */ }` }; }
        }
    },

    // --- MAIN PROCESS ---

    processRequest(query, intentAnalysis) {
        // 1. Analyze
        const language = this.detectLanguage(query);
        const topic = this.extractTopic(query);

        console.log(`[CodingEngine PRO] Language: ${language}, Topic: ${topic}`);

        // 2. Select Strategy
        let strategy = this.strategies[language];

        // Fallback checks
        if (!strategy && (language === 'javascript' || language === 'js')) strategy = this.strategies.node;
        if (!strategy) strategy = this.strategies.python;

        // 3. Generate Project Files
        // Pass 'this' as engine context for helper methods
        const projectFiles = strategy.generate(topic, query, this);

        // 4. Auto-Generate README if not present
        if (!projectFiles['README.md'] && !language.includes('html') && !language.includes('game')) {
            projectFiles['README.md'] = `# ${topic}\nGenerated by Guahh AI.\nRun the main file to start.`;
        }

        // 5. Format for Chat Interface
        return this.formatResponse(projectFiles, topic, language);
    },

    formatResponse(files, topic, language) {
        let response = `I've created a **${topic}** project. \n\n`;

        for (const [filename, content] of Object.entries(files)) {
            let lang = filename.split('.').pop();
            // Map extensions
            if (lang === 'js' || lang === 'jsx') lang = 'javascript';
            if (lang === 'py') lang = 'python';
            if (lang === 'md') lang = 'markdown';
            if (lang === 'rb') lang = 'ruby';

            response += `### 📄 ${filename}\n`;
            response += `\`\`\`${lang}\n${content}\n\`\`\`\n\n`;
        }

        return {
            text: response,
            sources: ["Guahh Code Pro"]
        };
    }
};

window.GuahhCodingEngine = GuahhCodingEngine;
